### ISSUE TITLE
Can't pull wpilib/raspbian-cross-ubuntu image from dockerhub

### ISSUE THREAD

**Issue by nathanmutin** [wpilibsuite/docker-images#1]
## Description of the issue

This issue is directly related to images on docker hub (https://hub.docker.com/r/wpilib/raspbian-cross-ubuntu/)

Users can't pull the image from docker. Missing the image with tag latest
Context information (for bug reports)

## Steps to reproduce the issue

1. `docker pull wpilib/raspbian-cross-ubuntu`
2. Observe the error in terminal

## Observed result

The error in terminal
```
→ docker pull wpilib/raspbian-cross-ubuntu
Using default tag: latest
Error response from daemon: manifest for wpilib/raspbian-cross-ubuntu:latest not found
```

## Suggested solution

In each stable relase push container with the `latest` tag.

**Comment by PeterJohnson** [comment]
For these images it’s not a good idea to have a “latest” tag, because the compilers installed change names with each release.  To pull down a specific tag version, append `:tag` to the repo name.
